keywords = [
    " a tesla", " vegan", "acute drought", "afforestation", "ailing world",
    "alternative energ", "apocalyptic futu", "apocalyptic scen", "apocalyptic world", "arctic melt",
    "artificial rain", "bio econom", "biodiveristy loss", "biomass energ", "biomass power",
    "carbon account", "carbon assess", "carbon audit", "carbon captur", "carbon compensa",
    "carbon credit", "carbon cycle", "carbon econom", "carbon effic", "carbon emission",
    "carbon farm", "carbon footprint", "carbon label", "carbon management", "carbon neutral",
    "carbon offset", "carbon pricing", "carbon reduct", "carbon remov", "carbon sequestr",
    "carbon storage", "carbon strateg", "carbon track", "carbon trad", "carbon-conscious",
    "carbon-negative", "carbon-positive", "catastrophic futu", "catastrophic scen", "ch4 concentra",
    "ch4 emission", "changing climate", "circular carbon", "circular econom", "circular produc",
    "civilization collaps", "clean energ", "climate action", "climate activis", "climate adapt",
    "climate advoca", "climate agreement", "climate ambass", "climate apocal", "climate art",
    "climate assess", "climate aware", "climate blog", "climate campaign", "climate champion",
    "climate change", "climate chaos", "climate charit", "climate coalition", "climate communicat",
    "climate conference", "climate consultant", "climate crisis", "climate data", "climate defend",
    "climate demonstrat", "climate document", "climate educat", "climate education", "climate educator",
    "climate emergenc", "climate entrepr", "climate exhibit", "climate expert", "climate fiction",
    "climate finance", "climate foundation", "climate goal", "climate hero", "climate impact",
    "climate influenc", "climate initiat", "climate innovat", "climate intervention", "climate invest",
    "climate journal", "climate justice", "climate leader", "climate legisla", "climate litera",
    "climate march", "climate migrant", "climate mitigat", "climate mob", "climate model",
    "climate movement", "climate movie", "climate network", "climate ngo", "climate organis",
    "climate organiz", "climate phenomen", "climate pioneer", "climate polic", "climate predict",
    "climate protest", "climate rall", "climate refuge", "climate report", "climate research",
    "climate resilien", "climate revolt", "climate risk", "climate science", "climate scientist",
    "climate solution", "climate speaker", "climate steward", "climate storytell", "climate strike",
    "climate summit", "climate system", "climate target", "climate tech", "climate variab",
    "climate vision", "climate volunt", "climate warm", "climate warrior", "climate-friend",
    "cloud seed", "co2 concentramethane emission", "co2 emission", "co2 level", "co2 reduct",
    "coastal erosion", "collapsing ecosystem", "collapsing society", "collapsing world", "conscious consum",
    "consumerism", "cooperative communit", "cooperative product", "crumbling planet", "decarbon",
    "decaying world", "declining world", "degrading planet", "degrowth", "desertific",
    "deteriorating environment", "doomed planet", "eco anarchis", "eco anxi", "eco aware",
    "eco centric", "eco consci", "eco distress", "eco fascis", "eco socialis",
    "eco-centric", "eco-friend", "eco-turis", "ecological adapt", "ecological balanc",
    "ecological conservat", "ecological crisis", "ecological degrad", "ecological economic", "ecological footprint",
    "ecological impact", "ecological integr", "ecological resilien", "ecological restor", "ecological solution",
    "ecological sustain", "ecological tech", "ecosystem destruction", "electric SUV", "electric car",
    "electric mobil", "electric vehicle", "electrical mobil", "endangered earth", "energy crisis",
    "energy transit", "environmental", "eroded ecosystem", "greta thunberg", "ethical consum", "ethical manufact",
    "ethical produc", "existential threat", "extinction rebel", "extractivis", "extrem weather",
    "extreme drought", "extreme event", "fading biosphere", "fading gaia", "floating cit",
    "flood protection", "flood risk", "flood threat", "flood warning", "food crisis",
    "food scarcity", "forest plantation", "forest recov", "fossil capital", "fossil fuel",
    "fragile ecosystem", "fridays for future", "garden cit", "geothermal energ", "geothermal power",
    "glacier melt", "global temperature", "global warming", "green arquitect", "green construct",
    "green consum", "green energ", "green futurgreen cit", "green job", "green life",
    "green lives", "green living", "green party", "green peace", "green pract",
    "green produc", "green techeco turis", "greenhouse effect", "greenhouse gas", "greenpeace",
    "greenwash", "harsh drought", "heat pump", "heat wave", "hotter climate",
    "hotter ocean", "hotter planet", "hotter season", "human displac", "humanitarian crisis",
    "humanitarian disaster", "hydro energ", "hydro power", "increasing sea", "intense drought",
    "ipcc", "land submer", "lithium batter", "locally source", "low-carbon",
    "mass extinct", "melting glaci", "melting ice", "melting polar", "melting pole",
    "methane emission", "moribund earth", "natural disaster", "nature-based", "neo extractivis",
    "neoextractivis", "net zero", "net-zero", "non-renewable", "nowtopia",
    "paris agreement", "passive solar", "perishing planet", "plant based", "plant-based",
    "plantation forest", "planting trees", "plastic free", "plastic-free", "polar melt",
    "prolonged drought", "recycling", "reforestation", "regenerative agriculture", "renewable energ",
    "renewable material", "renewable produc", "resource depletion", "responsible consum", "rewilding",
    "rising sea", "rooftop windmill", "sand batter", "sdg", "sea level ris",
    "sea rise", "seeding cloud", "severe drought", "severe weather", "shorline erosion",
    "slow fashion", "sociatal collaps", "solar energ", "solar glass", "solar panel",
    "solar power", "solarpunk", "sustainability", "sustainable agricultur", "sustainable architect",
    "sustainable business", "sustainable cit", "sustainable construct", "sustainable consumption", "sustainable design",
    "sustainable develop", "sustainable econom", "sustainable energ", "sustainable environment", "sustainable farm",
    "sustainable financ", "sustainable fish", "sustainable food", "sustainable forest", "sustainable futur",
    "sustainable goal", "sustainable growth", "sustainable industr", "sustainable initiativ", "sustainable innovat",
    "sustainable invest", "sustainable li", "sustainable manufact", "sustainable material", "sustainable mobil",
    "sustainable planet", "sustainable polic", "sustainable practi", "sustainable produc", "sustainable project",
    "sustainable seafood", "sustainable solut", "sustainable techn", "sustainable transport", "sustainable urban",
    "terminal planet", "tidal energ", "tidal flood", "tidal power", "tragic futur",
    "tree plantation", "tree planting", "tree seed", "unprecedented catastro", "vegetarian",
    "waning earth", "warmer climate", "warmer ocean", "warmer season", "water scarcity",
    "wave energ", "wave power", "weater control", "weather alert", "weather crisis",
    "weather disaster", "weather disturb", "weather emergenc", "weather event", "weather manipul",
    "weather modif", "weather phenomen", "weather warn", "wind energ", "wind farm",
    "wind power", "wind turbine", "wwf", "zero waste", "zero-emission",
    "zero-waste"
]
